kind: Service
apiVersion: v1
metadata:
  name: chart-repo
  namespace: prod
spec:
  selector:
    app: chart-repo
  ports:
    - protocol: TCP
      targetPort: 9421
      port: 9421
      name: https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chart-repo
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: chart.shannonai.com
    http:
      paths:
      - path: /
        backend:
          serviceName: chart-repo
          servicePort: 9421
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: chart-repo
  namespace: prod
  annotations:
      kubernetes.io/change-cause: "initial deployment"
  labels:
    app: chart-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chart-repo
  template:
    metadata:
      labels:
        app: chart-repo
    spec:
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
      - name: aliyun-shannon
      containers:
      - name: chart-repo
        image: registry.cn-beijing.aliyuncs.com/shannonai/file_server:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: https
          containerPort: 9421
